### ISSUE TITLE
[Global] Content Import

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#1]
it would be great to have a way to get from `sitemap.xml` or some other list of URLs that encompass something like the results from a google search for `site:theblog.adobe.com` and turn those URLs into a set of `.md` files...

i think in this particular case a selector of `section#content` would probably be used to get to the content and then it looks a straight forward html to md conversion. 

from there i think it would be great to find a batch way to convert folder structure into `gdocs` or `.docx`

**Comment by kptdobe** [comment]
The import is straight forward.
This blog post https://theblog.adobe.com/new-data-governance-capabilities-in-adobe-experience-platform-help-brands-manage-data-better/
would easily give this markdown:
https://github.com/kptdobe/helix-htmlimporter/blob/master/content/output/b1.md

To not overload the md, there is some processing to do on the html (with JSOM and jquery it is super simple!): https://github.com/kptdobe/helix-htmlimporter/blob/master/index.js#L18-L31

For now I do a random transformation to isolate the author and the topics at the end in own sections, I know it will not be the final output but this illustrates how easy it is.
We'll need to separately extract the author info, they are most likely coming from somewhere else and aggregated server side. Will have to do something similar in a special section at the end.

@rofe Once we know the required structure for a blog md file, I will adjust the processing.

All of this assuming the blog posts share the same dom. Which is already not the case for old ones but we can exclude those I assume.

**Comment by rofe** [comment]
Great! Looking at #3 and #4 I think we should strip the avatar and links from author and topics and keep them plain text. Link and avatar to the author's page would be added client-sided, as well as the links to products and topics.

**Comment by kptdobe** [comment]
Yes. While importing blog posts, I can also create the author and topic pages populated with content I find in each page (first one wins).
Working on it now.

**Comment by kptdobe** [comment]
Worked on the "real" download: https://github.com/kptdobe/helix-htmlimporter/tree/master/content/output/posts
For the selected live urls, downloads and converts everything necessary (html + imgs).
Now working on extracting author and topics.

**Comment by kptdobe** [comment]
I think blog pages now look like the expected final result (+/- some details). See examples in:

https://github.com/kptdobe/helix-htmlimporter/blob/master/content/output/posts/

Still TODO (on Monday): 
- create author pages during import
- create topics pages during import
- handle the "products in the page" if needed

**Comment by kptdobe** [comment]
Ok, was a good thing to test in onedrive... Multiple issues with storing `.md` files in onedrive:
- helix-pages does only render `.docx` files - we would need to implement a re-try (check first if `.docx` available, otherwise try `.md`. 
- you can read a `.md` file stored in onedrive but you cannot edit it nor export it to something else. Pure read-only.

This is blocking us for the import. The only elegant solution would be to create a `.docx` file instead of a `.md`.

**Comment by rofe** [comment]
How about just storing imported (i.e. static/past) posts directly as `.md` in the repo, and only render "new" posts from onedrive/`.docx`?

**Comment by kptdobe** [comment]
Good point. We can start like this.
I just populated the corresponding author pages. See https://github.com/kptdobe/helix-htmlimporter/tree/master/content/output/authors

**Comment by davidnuescheler** [comment]
regarding older blog posts... here is one i found from 2008.

https://theblog.adobe.com/conversion-success-events/

i think that ideally, no matter if new or old the md result should be the same...

**Comment by kptdobe** [comment]
We are lucky, the DOM is almost the same, the importer works as is: https://github.com/kptdobe/helix-htmlimporter/blob/master/content/output/posts/conversion-success-events.md

**Comment by tripodsan** [comment]
> Ok, was a good thing to test in onedrive... Multiple issues with storing `.md` files in onedrive:
> 
> * helix-pages does only render `.docx` files - we would need to implement a re-try (check first if `.docx` available, otherwise try `.md`.

this is relative simple to implement... this can be a feature for word2md

> * you can read a `.md` file stored in onedrive but you cannot edit it nor export it to something else. Pure read-only.

well, you can replace it...

> This is blocking us for the import. The only elegant solution would be to create a `.docx` file instead of a `.md`.

@davidnuescheler wdyt? should be convert the html back to docx?

**Comment by kptdobe** [comment]
Having the md files as static read-only documents in Onedrive does not bring much value (even if you could edit then via the onedrive folder on your desktop with your favorite md editor). I import the authors (bio), topics and soon the products, those will be "living" parts.

The HTML to MD convertion is easy and looks like a reverse pipeline (with a pre.js to interact with the DOM parts you may want to remove / patch). I looked at a HAST / MDAST to docx converter but it does not exist.
This would be cool :)

**Comment by tripodsan** [comment]
> Having the md files as static read-only documents in Onedrive does not bring much value (even if you could edit then via the onedrive folder on your desktop with your favorite md editor).

well, the impoted old posts are not modified anymore. hence could be considered as _archived_

>  I import the authors (bio), topics and soon the products, those will be "living" parts.

this could be a one-by-one bases. If an author wants to edit his bio, he can copy-base the md in a word doc. that is probably easier.

the topics are a manually crafted "sitemap". those don't need to by dynamic.

> The HTML to MD convertion is easy and looks like a reverse pipeline (with a pre.js to interact with the DOM parts you may want to remove / patch). I looked at a HAST / MDAST to docx converter but it does not exist.

there are a ton of docx generation libraries. eg https://www.npmjs.com/package/docx looks simple enough. writing to mdast2docx should be too difficult.

**Comment by kptdobe** [comment]
Yes, that's basically the reverse operation of `helix-word2md`.

As a tmp step, I committed the current project state into a branch. Here is a test blog entry (still some styling work to be done:) https://alexonedrive--theblog--davidnuescheler.hlx.page/content/posts/four-paintings-that-show-what-you-can-do-in-adobe-fresco.html
Here is the corresponding md file: https://github.com/davidnuescheler/theblog/blob/alexonedrive/content/posts/four-paintings-that-show-what-you-can-do-in-adobe-fresco.md

I added https://github.com/adobe/helix-pages/issues/125 to be able to mix docx and md files together (currently not possible).

**Comment by kptdobe** [comment]
adobe/helix-pages#125 is blocking the work here since we cannot have `.md` and `.docx` in the same project.

**Comment by kptdobe** [comment]
Latest status: md can be imported, dumped into OneDrive / Google Docs and now rendered from there. 
Next issue: the images are imported together and must be rendered from OneDrive / Google Docs. See https://github.com/adobe/helix-word2md/issues/109.
Workaround: I changed the importer to B64 encode and inline the images in the md file. This works but makes the md unreadable...

**Comment by rofe** [comment]
For the demo, we could also just dump the .mds in the GH repo if that helps. We'd just have to find a way to index them.

cc @dominique-pfister

**Comment by tripodsan** [comment]
> Workaround: I changed the importer to B64 encode and inline the images in the md file. This works but makes the md unreadable...

can we change the importer to upload the images to azure instead?

**Comment by kptdobe** [comment]
I should be able to do that. Where do I find the `AZURE_BLOB_SAS` and `AZURE_BLOB_URI` params ?

**Comment by tripodsan** [comment]
> Where do I find the `AZURE_BLOB_SAS` and `AZURE_BLOB_URI` params ?

they are already params on the runtime helix-private package....

**Comment by kptdobe** [comment]
Well, the importer is for now a local cli. I would need to pass the params manually. I think the only thing I need is to be able to decrypt the secrets in project-helix. If you could add me as an admin there...

**Comment by kptdobe** [comment]
@tripodsan solution works like a charm. I can start feeding the legacy folder in OneDrive with existing blog posts as md files.

**Comment by kptdobe** [comment]
Legacy rendered from md: https://theblog--davidnuescheler.hlx.page/legacy/posts/creating-adobe-experience-platform-pipeline-with-kafka.html
Missing the products (again...).

**Comment by davidnuescheler** [comment]
closing for now
