### ISSUE TITLE
Lists from docx are not rendered as lists

### ISSUE THREAD

**Issue by kptdobe** [davidnuescheler/theblog#12]
Open http://localhost:3000/posts/adobe-named-a-leader-in-forresters-latest-enterprise-marketing-software-suites-report.html
and compare it to https://adobe.sharepoint.com/:w:/r/sites/TheBlog/_layouts/15/Doc.aspx?sourcedoc={a5292931-bdab-465f-9d85-7850955f9a65}&action=edit&wdPid=5b6014b6

Lists are not rendered as `ul / li` but just a set of lines.

**Comment by rofe** [comment]
Missing feature in `helix-word2md`?

**Comment by kptdobe** [comment]
Interestingly, list from https://adobe.sharepoint.com/:w:/r/sites/TheBlog/_layouts/15/Doc.aspx?sourcedoc=%7B740DD09C-6EF6-438E-BBD4-10FB4C02F669%7D&file=creating-adobe-experience-platform-pipeline-with-kafka.docx&action=default&mobileredirect=true works as expected.

**Comment by kptdobe** [comment]
Arff.. just recreated the lists in the faulty document and now it works as expected. This is so... fragile!
