### ISSUE TITLE
Handle "Products in this article"

### ISSUE THREAD

**Issue by kptdobe** [davidnuescheler/theblog#14]
Below author "section", you can find a "Products in this article" section. This product list is extracted in the main import as :

```
---
Topics: x y z
Products: a b c
```

at the end of the document and should be processed to appear below the author.

Example here: https://theblog.adobe.com/creating-adobe-experience-platform-pipeline-with-kafka/

**Comment by rofe** [comment]
Note that the topic handling currently assumes that `Topics: foo` is the last line and cuts off the rest of the text in the section. I'll change that to only remove the topics.

**Comment by kptdobe** [comment]
Current product handling is ok for a demo (links are not all working) but final implementation should be different: it should follow the same pattern than author, fetch the product page, retrieve logo / link / product name from product page and insert it from here. Creating all corresponding content in OneDrive is a fastidious task (all logo should be pasted inside the docx), will be done when architecture is clear and final. Will create followup ticket.
