### ISSUE TITLE
[Global] Polish the blog styling

### ISSUE THREAD

**Issue by kptdobe** [davidnuescheler/theblog#19]
Many details are not 1:1, like spacings, fonts... The overall styling must be reviewed and polished. This includes (not exhaustive):

- [ ] mobile version
- [ ] vertical title on the right side of the page

This excludes the Header and Footer, tackled here #2.

**Comment by davidnuescheler** [comment]
i quickly added a slightly different layout to represent the different layouts for mobile vs. desktop on the blog post and cleaned up some absolute positioning overlay issues with the author box.

in the process, i realized that this may only work if the entire post is in one section, which i think is a constraint that's fine for now, but it would be more appealing to wrap the body of the blog post into its own `div` to make the title, image, author, products, post, topics the direct descendants of `main`

**Comment by davidnuescheler** [comment]
closing for now
