### ISSUE TITLE
[Global] Header & Footer

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#2]
Clean up header and footer to be exact copies of the actual site

**Comment by kptdobe** [comment]
Todos are: 

Header
- [ ] styling
- [ ] add full nav entries(2 level lists for Topics and Products)
- [ ] fetch the "Recommanded For You" blog post (based on a link provided by author in header.md)
- [ ] search

Footer
- [ ] stying
- [ ] all links must be accurate

**Comment by davidnuescheler** [comment]
closing for now
