### ISSUE TITLE
[Posts] Indexing blog posts

### ISSUE THREAD

**Issue by rofe** [davidnuescheler/theblog#23]
Several features require a search index for blog posts.

**Comment by rofe** [comment]
In order to display excerpts in the article lists, it would be great if we could also index the first 20 words (or ~130 characters cut after last blank).

**Comment by rofe** [comment]
I think all that's still missing here now is the auto-index on content modifications, right @dominique-pfister?

**Comment by tripodsan** [comment]
and the clientside code to extract the teaser.

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-word2md/issues/115

**Comment by dominique-pfister** [comment]
Yep, we can close this one.
