### ISSUE TITLE
[Global] Onedrive "connector" is not stable

### ISSUE THREAD

**Issue by kptdobe** [davidnuescheler/theblog#27]
I see inconsistent behaviours when working locally on the project and reloading frequently various the pages we have (like http://localhost:3000/posts/creating-adobe-experience-platform-pipeline-with-kafka.html). In the `hlx up` logs, I see errors like: 

```
[hlx] error: Error while fetching Markdown from https://adobeioruntime.net/api/v1/web/helix/helix-services/word2md@latest?rid=9LMbVX53YZ22tg%2BP71%2BMuW14IJYsc%2FhB&src=helix%2Fgithub.com--davidnuescheler--theblog%2Fproducts&path=%2Fhead.docx&shareLink=https%3A%2F%2Fadobe.sharepoint.com%2Fsites%2FTheBlog%2FShared%2520Documents%2Ftheblog%3Fcsf%3D1%26e%3D8Znxth with the following options:
{ uri:
   'https://adobeioruntime.net/api/v1/web/helix/helix-services/word2md@latest?rid=9LMbVX53YZ22tg%2BP71%2BMuW14IJYsc%2FhB&src=helix%2Fgithub.com--davidnuescheler--theblog%2Fproducts&path=%2Fhead.docx&shareLink=https%3A%2F%2Fadobe.sharepoint.com%2Fsites%2FTheBlog%2FShared%2520Documents%2Ftheblog%3Fcsf%3D1%26e%3D8Znxth',
  json: false,
  timeout: 10000,
  time: true,
  followAllRedirects: true }
```

Looking at Coralogix, I also see plenty of messages like this (INFO, not ERROR): 

```

{"message":"Error while converting document: %s { StatusCodeError: 404 - 

```

Maybe @tripodsan can help here.

**Comment by rofe** [comment]
Since this morning, I'm not getting anything rendered anymore :( 
Same console output as above.

**Comment by rofe** [comment]
if you hit https://adobeioruntime.net/api/v1/web/helix/helix-services/word2md@latest?rid=4xxbLM72Cz5E%2FJ0Spd4DwEi9S%2FUnHGxo&src=helix%2Fgithub.com--davidnuescheler--theblog%2Fhomepage&path=%2Findex.docx&shareLink=https%3A%2F%2Fadobe.sharepoint.com%2Fsites%2FTheBlog%2FShared%2520Documents%2Ftheblog%3Fcsf%3D1%26e%3D8Znxth repeatedly, you will get AZURE_WORD2MD_CLIENT_ID parameter missing` every other time...

**Comment by tripodsan** [comment]
this is no longer the case.
