### ISSUE TITLE
[CDN] Set Up CDN

### ISSUE THREAD

**Issue by trieloff** [davidnuescheler/theblog#29]
Hostname: `theblog.helix-demo.xyz`
Backends:
- Fastly (Helix Pages)
- Algolia (`/_query/…`)

Caching:
- some (not too much)

**Comment by trieloff** [comment]
I'd assign myself.

**Comment by trieloff** [comment]
<img width="1237" alt="Screen Shot 2020-01-06 at 10 58 58" src="https://user-images.githubusercontent.com/39613/71810867-a40e6300-3073-11ea-973e-3cf3af9f535f.png">

Lighthouse score on desktop is ok now.

**Comment by rofe** [comment]
@trieloff , can this be closed?

**Comment by davidnuescheler** [comment]
just for the sake of comparison, i have setup cloudflare as promised... on

https://theblog.page/

@trieloff, i think the desktop performance is great, but i'd rather use the mobile score, as it is more sensitive to latency and we possibly are looking at a majority of the traffic coming from mobile.

i'll create a new issue for page speed so we can track things there...
