### ISSUE TITLE
Tags / Topic

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#3]
I think tags should be added in a simple way by an author just adding 

`Topics: Customer Experience, Campaign Management`

at the very end of the document.

As this is below the fold i think client sided manipulation of the DOM should be perfectly fine to create the "Topics" experience

Indexing would have to be adapted to be able to deal with this new way of specifying tags/topics.

Showing all posts for a specific topic/tag i could see a default way of dealing with it, intuitively something like `/topic.html?topic=Campaign+Management` but ideally we also support `/topics/campaign-management.html` where we could similar to authors optionally have a little description on the topic / product.

**Comment by rofe** [comment]
How to try it out:
1. `git pull` on master
2. `hlx up`
3. open http://localhost:3000/posts/adobe-named-a-leader-in-forresters-latest-enterprise-marketing-software-suites-report.html
4. observe generated topic links at the bottom of the page
