### ISSUE TITLE
Google Drive integration

### ISSUE THREAD

**Issue by rofe** [davidnuescheler/theblog#33]
We want to showcase both OneDrive and Google Drive.

**Comment by kptdobe** [comment]
Reading the code, the support for both in one project would work if we have different mount points which means we can hardly mix content coming from both worlds. But at least we can have one entry point for each (like `/g` and `/ms` for example).

**Comment by stefan-guggisberg** [comment]
i'll take a stab at it, please assign me the issue

**Comment by rofe** [comment]
Cool! @davidnuescheler will need to invite you to the project.

**Comment by stefan-guggisberg** [comment]
Sorry, my misunderstanding. I thought this issue is about coding the integration.

**Comment by rofe** [comment]
Implemented with mount points `/g` and `/ms`. (The homepage currently redirects to `/ms`)
