### ISSUE TITLE
Running with "hlx run" fails with "Could not find Markdown" error and 404

### ISSUE THREAD

**Issue by bdelacretaz** [davidnuescheler/theblog#36]
fstab.json points to the an adobe.sharepoint.com URL which requires a login and permission, not sure if that's ok:

https://adobe.sharepoint.com/sites/TheBlog/Shared%20Documents/theblog?csf=1&e=8Znxth

Opening that URL with my Adobe credentials says "You need permission to access this item".

If I try to run theblog with "hlx run" I get this error which looks related and http://localhost:3000 returns a 404:

> [hlx] error: Could not find Markdown at https://adobeioruntime.net/api/v1/web/helix/helix-services/word2md@latest?rid=auACneEt2mwwuW29wnzHvl6EyuUu%2BKTf&src=helix%2Fgithub.com--davidnuescheler--theblog%2Fmaster&path=%2Findex.docx&shareLink=https%3A%2F%2Fadobe.sharepoint.com%2Fsites%2FTheBlog%2FShared%2520Documents%2Ftheblog%3Fcsf%3D1%26e%3D8Znxth

**Comment by kptdobe** [comment]
There is no `index.docx` at the root folder. This is work in progress (see #17). 

Check https://github.com/davidnuescheler/theblog#the-blog for working urls.
