### ISSUE TITLE
Authors

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#4]
I think authors should be added in a simple way by an author just adding 

```
by Bruce Swann
Posted on 11-18-2019
```

at the top of the document.

As this is below the fold i think client sided manipulation of the DOM should be perfectly fine to create the "Author" experience

Indexing would have to be adapted to be able to deal with this new way of specifying authors.

Showing all posts for a specific author i could see a default way of dealing with it, intuitively something like `/authors/bruce-swann.html` where we could have a bio written up and possibly have access to the prominent image as their headshot. alternatively, we could have all the authors images in separated out.

**Comment by kptdobe** [comment]
HTML rendering fixed with #9 
Will create follow up issues for other part to be handled like url handling.
