### ISSUE TITLE
Fix Lighthouse score issues

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#43]
this can be a container for things like #42 

i think we are at a good starting point, see below the mobile score of https://theblog.page for an individual blog post...

<img width="499" alt="Screen Shot 2020-01-06 at 4 23 37 PM" src="https://user-images.githubusercontent.com/5289336/71856568-9b348600-30a1-11ea-98d8-2d58774f7769.png">

**Comment by trieloff** [comment]
Do you use throttling for the mobile score? My throttled results are much worse than 96.

**Comment by davidnuescheler** [comment]
i am just using the standard google page speed insights settings...

**Comment by davidnuescheler** [comment]
i think we can back off of optimizing the lighthouse score for a little bit...

<img width="501" alt="Screen Shot 2020-01-07 at 4 17 15 PM" src="https://user-images.githubusercontent.com/5289336/71937415-7f94b280-3169-11ea-8926-8ff32f10b5cd.png">

**Comment by davidnuescheler** [comment]
the new homepage including the redirect had a significant impact on the lighthouse score...
it seems in some of my page speed requests include the query and some don't never the less here a couple screenshots...

<img width="647" alt="Screen Shot 2020-01-09 at 4 13 18 PM" src="https://user-images.githubusercontent.com/5289336/72112564-25c3f200-32fb-11ea-8f2f-9f4185234daf.png">
<img width="647" alt="Screen Shot 2020-01-09 at 4 13 40 PM" src="https://user-images.githubusercontent.com/5289336/72112565-25c3f200-32fb-11ea-8f77-50b984e96f26.png">
<img width="640" alt="Screen Shot 2020-01-09 at 4 14 13 PM" src="https://user-images.githubusercontent.com/5289336/72112567-265c8880-32fb-11ea-895a-b6a915f6ea9e.png">

the way this looks now i think we would significantly benefit from routing the images through fastly and resizing them to the right size as well as modern formats....

also, i think we should get rid of the `/ms` redirect at least in the short-term... i think it is fine for now if the homepage is in github

**Comment by rofe** [comment]
> also, i think we should get rid of the `/ms` redirect at least in the short-term... i think it is fine for now if the homepage is in github

Done in cb8a0dc5d9d89b800835166783e4130451d3c6a2

**Comment by rofe** [comment]
Another thing to maybe consider is that our current Algolia index is located in Europe, which might have an effect on performance from the US...

**Comment by davidnuescheler** [comment]
i don't think that this should be the issue... i think page speed insights doesn't always account for the actual posts being loaded as it happens on `window.onload()`... you can tell if it did or if it didn't by looking at the resulting page that's rendered...

<img width="959" alt="Screen Shot 2020-01-10 at 9 27 08 AM" src="https://user-images.githubusercontent.com/5289336/72169160-ceba2d80-338b-11ea-8e51-9445a7293a3c.png">

if i look at the major opportunity, then it is properly resized images which definitely should be unrelated to the latency of the algolia response...

**Comment by davidnuescheler** [comment]
i went back and looked at the current setup and while we are getting to >80 i would like for this to be north of 90....

<img width="451" alt="Screen Shot 2020-01-14 at 4 31 05 PM" src="https://user-images.githubusercontent.com/5289336/72394507-62bd2980-36eb-11ea-81af-20d6d95e3173.png">

i think the best way forward would obviously be to fix those by routing them through fastly, alternatively we can look for different routes for the short term...

**Comment by trieloff** [comment]
Routing images through Fastly (and turning them into next-gen formats on the fly) has been merged to Helix Publish: https://github.com/adobe/helix-publish/pull/278 – I'm adjusting the URLs in word2md and gdocs2md next.

**Comment by kptdobe** [comment]
I assume I'll have to adjust the importer with the same url, update all existing md files and re-index all blog posts...

**Comment by trieloff** [comment]
@kptdobe I don't think this will affect the importer at all – unless I'm missing something. The changes to gdocs and word2md will only affect the output.

**Comment by kptdobe** [comment]
Well, the https://theblog--davidnuescheler.hlx.page homepage contains only images from blog posts imported from existing site which I upload in the Azure Blob Storage too (I copied the logic from word2md). Urls are like: https://hlx.blob.core.windows.net/external/0e618e43eb2d873e65385bbf169e2d7c4f77776e and I assume using your stuff is the only way to make it faster. Otherwise I misunderstood what you are doing.

**Comment by rofe** [comment]
@kptdobe is correct: the hero images of blog posts displayed on the homepage and author pages are coming from the index, which takes it from the HTML output. So if those URLs change, we'll need a re-index.

**Comment by kptdobe** [comment]
Just a minor correction: all images from the blog posts imported as markdown are coming from the Azur Blog Store.

**Comment by trieloff** [comment]
Ok, then we have to re-index, as the URLs change, but not re-import, as the storage location stays the same.

**Comment by kptdobe** [comment]
Does not work (yet): 
- https://hlx.blob.core.windows.net/external/85485645c8ecdea305e5eb61a157ebae66f7fd9e ok
- https://theblog--davidnuescheler.hlx.page/hlx_85485645c8ecdea305e5eb61a157ebae66f7fd9e no ok

**Comment by kptdobe** [comment]
https://theblog--davidnuescheler.hlx.page/hlx_85485645c8ecdea305e5eb61a157ebae66f7fd9e.jpg ok :)

**Comment by trieloff** [comment]
Yes, the `jpg` (or `png` or `webp` or `gif`) ending is mandatory.

**Comment by kptdobe** [comment]
I updated the 2020 pages and re-run the lighthouse tests: while the perceived loading time is much better, the tests results are not better! (on https://theblog--davidnuescheler.hlx.page/):

![Screenshot 2020-01-15 at 11 13 21](https://user-images.githubusercontent.com/474200/72425540-46bb9580-3788-11ea-8bb8-f4eda9b46c2d.png)

**Comment by kptdobe** [comment]
Couldn't we run the Fastly image optimization service on those images ? (if this helps)

**Comment by kptdobe** [comment]
@rofe complains that having image urls like `/hlx_85485645c8ecdea305e5eb61a157ebae66f7fd9e.jpg` in the content does not work locally!
We should update prepend the domain to all images. But what is the domain we'll use for the demo ?

**Comment by kptdobe** [comment]
For now, I am going to prepend `https://theblog--davidnuescheler.hlx.page/`, I can replace when we have a final domain name decision.

**Comment by trieloff** [comment]
@rofe @kptdobe the correct solution is to backport adobe/helix-publish#278 to `helix-simulator`

**Comment by kptdobe** [comment]
The lighthouse thingy is not really... reliable! I manually optimized the 2 first big images to see if this improves. After image 1 optimisation, I went from 64 to 67. After image 2 optimisation, I went from 67 to... 64. I re-run the test and now I have 68...! Now it is stable to 68.

**Comment by davidnuescheler** [comment]
the lighthouse score is definitely a snapshot and especially given our current state with caching it is expected to hover quite a bit... i think the detailed descriptions are much more stable though...

**Comment by rofe** [comment]
Both homepage and post page are consistently in the 90s now.
