### ISSUE TITLE
[Author] Show latest posts on the author page

### ISSUE THREAD

**Issue by kptdobe** [davidnuescheler/theblog#47]
https://theblog--davidnuescheler.hlx.page/authors/donna-morris.html
vs
https://theblog.adobe.com/author/donnamorris

At the bottom of the page, the latest posts from an author are displayed.

**Comment by rofe** [comment]
We already have that, sort of. It’s just that this author doesn’t have any (indexed) articles yet.

Check out https://theblog--davidnuescheler.hlx.page/authors/suresh-vittal.html for an example.

**Comment by rofe** [comment]
See #22
