### ISSUE TITLE
[Posts] Drafts vs. publishing

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#5]
i think at this stage it would be great if we just have a `/drafts` vs. a `/posts` folder and publishing essentially just means moving things in one drive / sharepoint

**Comment by rofe** [comment]
We do have `drafts` and `posts` folders in the shared OneDrive folder. So we could consider this issue resolved :)

One remaining question is if and how we could further limit access to drafts (I mean in addition to the hard-to-guess URLs). I was thinking we could maintain a branch (e.g. `authoring`) of this repo pointing to the `/drafts` folder, and have authors use its Helix Pages URL to preview content during creation, whereas the master keeps pointing to `/posts` and only delivers the published posts.

For example, a blog author would work on her `/drafts/new-post.docx` in OneDrive and use the following URL to preview:
`https://authoring--theblog--adobe.hlx.page/drafts/new-post.html` 
Once moved to the `/posts` folder in OneDrive, it would become available under
`https://theblog--adobe.hlx.page/posts/new-post.html`

Dedicated Fastly services (e.g. `theblog-authoring.adobe.com` and `theblog.adobe.com`) could mask the Helix Pages URLs and add caching.

Downsides: the authoring branch would keep running out of sync with the master branch, and smart people might still figure out how to get access to unpublished content (unless we filter IPs at Fastly level?)

@davidnuescheler @kptdobe wdyt?

**Comment by rofe** [comment]
I think we can close this for now. The exact publishing workflow to use will be determined as part of the project's discovery and/or user testing phase.
