### ISSUE TITLE
[Global] Move author div computation to "something server side"

### ISSUE THREAD

**Issue by kptdobe** [davidnuescheler/theblog#8]
Upcoming change https://github.com/davidnuescheler/theblog/blob/alexonedrive/head.html#L32-L65 deals with the "by AUTHOR" text in the DOM, fetch the author avatar and construct the expected DOM for an author. This is a decent amount of logic which is run client side. Which means this final DOM will not be cached by Fastly and we be recomputed on each request.
This could be moved into a `pre.js` but we are using `helix-pages` here which does not support it. https://github.com/adobe/helix-pipeline/issues/516 will introduce one step into this direction but not enough to cover this use case (see my comment there).

**Comment by kptdobe** [comment]
The author request when the file is stored in onedrive is so slow that you see the author appearing later on... see https://author--theblog--davidnuescheler.hlx.page/posts/adobe-named-a-leader-in-forresters-latest-enterprise-marketing-software-suites-report.html

**Comment by tripodsan** [comment]
@kptdobe why do you need an extra (onedrive) request for this? every thing you need to know should be available either from the markdown or the query.

**Comment by kptdobe** [comment]
> everything you need to know should be available either from the markdown

That's the problem, it is not. The blog post markdown contains only the name of the author. Via Helix-Pages, only way to resolve the author's avatar is, base on this name, compute the author page path, make a new request from the client to get the author page and inject the image into the current dom.
And this is true for any resolution that needs to happen (like icons of product list...). We already have multiple of them, then multiple extra requests to onedrive.

In production, each of these requests will be cached but the blog post final dom will not be, it will have to be recomposed for each surfer accessing every single blog post entry...

**Comment by tripodsan** [comment]
I would imagine,

```
by Major Domo
```

--> `src="/autors/major_domo/avatar.png"`

**Comment by tripodsan** [comment]
> (like icons of product list...)

why? the icons are not stored in one-drive, they are given by the designer.

**Comment by kptdobe** [comment]
Yes and no. This could be one approach but requires a lot of discipline for the authors to create their bio (must be a png, must be named avatar...).

For the author and the products, we need a bit more than the image:
- author biography
- product link to the adobe.com site

Thus to store this content, we need to create page per author and per product which then I think should contain all content, including the image / logo, a potential display name (including accents, job title...), bio / product description. This also allows to have an entry point from requests `/authors/major_domo.html` which has to be served anyway.

From there, 1. it is not only about the image only 2. we cannot compute the image path automatically because it is stored in the docx file.

Another thing is that for now, you cannot store anything else than .docx (and soon .md) in OneDrive / Google Doc. Having images in Git and bio in OneDrive does not make sense.

**Comment by tripodsan** [comment]
> Another thing is that for now, you cannot store anything else than .docx (and soon .md) in OneDrive / Google Doc. Having images in Git and bio in OneDrive does not make sense.

the author images are uploaded to azure anyways during processing. and those remain stable. so the  index can store the image urls as a property for the author page.

**Comment by kptdobe** [comment]
Our discussion today led to the following conclusion: all content collection and mapping should happen via the index (see #23): we'll then have only one extra request to Algolia and the client side code will only feed the dom with the content provided from here.
