### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by rofe** [davidnuescheler/theblog#81]
Implement `sitemap.xml`.

**Comment by rofe** [comment]
https://github.com/adobe/helix-home/issues/90

**Comment by trieloff** [comment]
I'll take care of the `cgi-bin`

**Comment by trieloff** [comment]
https://github.com/adobe/helix-publish/issues/88

**Comment by rofe** [comment]
Done: https://theblog.helix-demo.xyz/sitemap.xml
