### ISSUE TITLE
Implement Global Navigation

### ISSUE THREAD

**Issue by rofe** [davidnuescheler/theblog#82]
The FEDS (Federated Services) library providing standard adobe.com features:
- [x] IMS sign up/in
- [x] geo detection
- [x] consent management*
- [ ] blog specific nav*

* need to be configured in dedicated FEDS experience (see #91)

**Comment by MarquiseRosier** [comment]
@rofe is that supposed to be content management?

**Comment by tripodsan** [comment]
@rofe why is this global navigation?

**Comment by rofe** [comment]
No this is the standard client side navigation used on all adobe.com web properties.

**Comment by rofe** [comment]
Started the onboarding process to whitelist the necessary Helix domains.

**Comment by rofe** [comment]
WIP: https://feds--theblog--davidnuescheler.project-helix.page/

todo:
- [ ] blog specific nav

**Comment by rofe** [comment]
IMS login integrated

**Comment by rofe** [comment]
We decided to go without a custom experience for now. Done.

**Comment by rofe** [comment]
Blog specific nav is live
