### ISSUE TITLE
Faster Fonts

### ISSUE THREAD

**Issue by trieloff** [davidnuescheler/theblog#92]
Try the new, faster font delivery by removing the JS-based font loading and instead use `https://theblog-davidnuescheler.hlx.page/hlx_fonts/lkg3fdt.css` as the font source.

**Comment by auniverseaway** [comment]
Is the project not using Adobe Fonts (Typekit)? Should probably move to it. We have kits for adobe.com that have been optimized to drop one of the tracking pixels that you typically get from most TK integrations.

**Comment by rofe** [comment]
Just realized after merging #95 that even though the kit https://theblog-davidnuescheler.project-helix.page/hlx_fonts/pnv6nym.css is loading fine, all subsets in it give 404s, e.g.
https://theblog-davidnuescheler.project-helix.page/hlx_fonts/af/b0c5f5/00000000000000003b9b3f85/27/l?subset_id=2&fvd=n4&v=3

@trieloff

**Comment by rofe** [comment]
The same works when requested directly via typekit: https://use.typekit.net/af/b0c5f5/00000000000000003b9b3f85/27/l?subset_id=2&fvd=n4&v=3

**Comment by rofe** [comment]
@trieloff I think there's a bug in the rewriting of the subsequent URLs.

**Comment by trieloff** [comment]
Inspecting with `X-Debug` gives me the correct `X-Backend-URL`:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 0
Cache-Control: max-age=604800, public
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 36
Content-Type: application/json; charset=utf-8
Date: Tue, 11 Feb 2020 17:07:14 GMT
Strict-Transport-Security: max-age=31536000
Vary: X-Debug,X-Strain,X-Request-Type
Via: 1.1 varnish
X-Backend-Name: 3l2MjGcHgWw5NUJz7OKYH3--F_AdobeFonts
X-Backend-URL: /af/d91a29/00000000000000003b9af759/27/l?primer=34645566c6d4d8e7116ebd63bd1259d4c9689c1a505c3639ef9e73069e3e4176&fvd=i4&v=3
X-CDN-Request-ID: b86ac0d6-8d5a-4c6f-9f54-5db304e090b9
X-Cache: MISS
X-Cache-Hits: 0
X-FullDirname: /hlx_fonts/af/d91a29/00000000000000003b9af759/27/l
X-Github-Static-Ref: @(null)
X-Orig-URL: /hlx_fonts/af/d91a29/00000000000000003b9af759/27/l?primer=34645566c6d4d8e7116ebd63bd1259d4c9689c1a505c3639ef9e73069e3e4176&fvd=i4&v=3
X-Powered-By: Express
X-Request-Type: Fonts
X-Served-By: cache-bur17576-BUR
X-Strain: default
X-Timer: S1581440834.478636,VS0,VE299
X-Trace: vcl_recv; hlx_recv_init; hlx_strain(resolved); hlx_block_recv; hlx_deny; hlx_allow; hlx_determine_request_type(fonts)(none); hlx_type_fonts; vcl_hash(www.primordialsoup.life/hlx_fonts/af/d91a29/00000000000000003b9af759/27/l?primer=34645566c6d4d8e7116ebd63bd1259d4c9689c1a505c3639ef9e73069e3e4176&fvd=i4&v=3); vcl_miss(www.primordialsoup.life/hlx_fonts/af/d91a29/00000000000000003b9af759/27/l?primer=34645566c6d4d8e7116ebd63bd1259d4c9689c1a505c3639ef9e73069e3e4176&fvd=i4&v=3); hlx_bereq; vcl_fetch(200: /hlx_fonts/af/d91a29/00000000000000003b9af759/27/l?primer=34645566c6d4d8e7116ebd63bd1259d4c9689c1a505c3639ef9e73069e3e4176&fvd=i4&v=3 Fonts); vcl_deliver; hlx_headers_deliver; hlx_deliver_errors; hlx_deliver_type(Fonts)
X-URL: /hlx_fonts/af/d91a29/00000000000000003b9af759/27/l?primer=34645566c6d4d8e7116ebd63bd1259d4c9689c1a505c3639ef9e73069e3e4176&fvd=i4&v=3
X-Version: 1250; src=1249; cli=3.3.4; rev=online
```

and inspecting with RequestBin, everything seems normal. In fact, when I create the same request (same parameters and headers) from my client, everything is going through the way we want:

**Comment by trieloff** [comment]
@drwilco and I are seeing strange behavior right now: URLs that will consistently 404 will consistently 200 after we take a not yet understood action on the client side.

**Comment by trieloff** [comment]
Waiting for confirmation from @rofe

**Comment by rofe** [comment]
@trieloff confirmed
